name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Requirements
        run:
          pip install -r requirements.txt
      - name: Lint
        run:
          pylint src/
      - name: Format
        run:
          black --check ./
      - name: Type Check
        run:
          mypy src --strict
      - name: Unit Tests
        run:
           python -m pytest tests/unit